"""initial_tables

Revision ID: 4c0750c1853b
Revises:
Create Date: 2025-09-14 21:38:06.855824

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4c0750c1853b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
